### ISSUE TITLE
Primer semana de repaso?

### ISSUE THREAD

**Issue by aloctavodia** [LCD-UNSAM/estadistica_e_inferencia_II#2]
Creo que la primer semana podríamos usarla para un repaso de conceptos muy generales y para repasar/presentar el uso de los paquetes PyMC, ArviZ y PreliZ. Me parece que tomarse esta semana para esa tarea nos ahorrará tiempo en las siguinetes semanas. 

Con ese fin es que he agregado los notebooks 01 y 02. El 1 sería la "teoría" (aunque al final contiene algunos ejercicios) y el "2" sería principalmente ejercicios.

De todas formas por el momento los dejaría como están y me concentraría en los notebooks >= 3. Cuando inferencia I esté por finalizar y tendremos más claro que temas han visto y creo que será más fácil trabajar esos dos primero notebooks

**Comment by exord** [comment]
Me parece clave arrancar con un buen repaso de las cosas vistas hasta el momento y presentar cómo se encadenan esos contenidos con los de esta materia.

**Comment by aloctavodia** [comment]
Buenísimo, entonces tenemos consenso sobre empezar con un repaso!
